### ISSUE TITLE
Unlock some more websites

### ISSUE THREAD

**Issue by aloner-pro** [vivek9patel/economist.com-unlocked#1]
This is a very _**good project**_. I don't know much of _Javascript_ otherwise I would have contributed. Go on !!
From a _**17 yr**_ old.

**Comment by vivek9patel** [comment]
Some websites only allow requests with same_origin Header, that's why it cannot be displayed in iframe!
Glad you liked my project!

**Comment by nihaladoni** [comment]
Please add support for medium articles.

**Comment by immayurpanchal** [comment]
@vivek9patel I would like to contribute to this and any other project to unlock and read the articles. Please reply on this thread. We can connect. I'm a React Enthusiast.I would love to work any project written in Vanilla JavaScript, React, NodeJS, Python. Really impressed with your portfolio website. Awesome 😎 work. Keep it up man!

**Comment by vivek9patel** [comment]
If you can tell me what do you want to add in this project, like any features, or resolving any bugs, that'll be useful!

**Comment by aloner-pro** [comment]
can you unlock Medium, Quartz , The New York Times ?

**Comment by vivek9patel** [comment]
will try!

**Comment by Xmaspro** [comment]
It's a excellent extension.
